First part was implemented
Mandybur800/jv-create-annotation pull request #1
Opened 2021-01-06 22:14 UTC by Mandybur800

2021-01-07 09:31 UTC, Artificial-Friend approved these changes

2021-01-07 09:36 UTC, Artificial-Friend approved these changes

2021-01-07 09:36 UTC, Artificial-Friend commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            } catch (NumberFormatException e) {
Try to write any single number and press `Enter`

2021-01-08 10:14 UTC, dmytro-hryhoruk requested changes

2021-01-08 10:14 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.add(bet);
let's add bet only if it's not null

2021-01-08 10:14 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/model/Game.java
> +    private String team2;
don't user numbers in variables naming

2021-01-08 10:15 UTC, Mandybur800 commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.add(bet);
done

2021-01-08 10:17 UTC, Mandybur800 commented on src/main/java/core/basesyntax/model/Game.java
> +    private String team2;
done

2021-01-08 14:05 UTC, dmytro-hryhoruk approved these changes

2021-01-08 14:25 UTC, merged